---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
#bibliography: [bibliography/references.bib, bibliography/additional-references.bib]
---

# Preface material {-}
\adjustmtc 
\chaptermark{Preface}
<!-- For PDF output, we must include this LaTeX command after unnumbered headings, otherwise the numbers in the mini table of contents will be incorrect -->

## Thesis format {-}

This thesis has been written to present data collected during the degree of Doctor of Philosophy as a coherent piece of work incorporating a series of stand-alone manuscripts.
Each manuscript is written according to the authorship guidelines of the journal that the manuscript is accepted for publication, submitted for review, or will be submitted to in the future. 
A statement of author attribution precedes each manuscript. 
All chapters are presented in a similar format with continuous referencing and table and figure numbering to maintain the continuity of the document.

This thesis is comprised of 7 chapters.
Chapter \@ref(litrev) comprises a literature review with an overview of ticks, tick-borne diseases and microorganisms.
In particular the review focuses on an Australian context and discusses the role of wildlife in the sylvatic cycle of microbes. 
Towards the end of chapter one the thesis aims are detailed \@ref(thesis-aims).  
The research chapters (2--6) are presented as individual scientific manuscripts and each contain their own abstract, introduction, materials and methods, results, and discussion. 
It is noted that as each research chapter is stand alone there are some repetitive aspects to this thesis. 
Modifications have been made to ensure consistency throughout this thesis and as such work presented here may differ slightly from any associated published work. 
The general discussion, chapter \@ref(gendiscussion) ties together major themes and findings presented in this thesis and provides a critical review on limitations and future directions.
To reduce redundancy some topics are not discussed in detail within the literature review and instead are included within the chapters.

All relevant data is made publicly available within this thesis. 
Data has been deposited to relevant repositories.
Nucleotide sequence data has been deposited to GenBank, raw Illumina MiSeq sequence data has been deposited to the NCBI sequence read archive (SRA). 
A data availability statement is provided at the start of each chapter.
Additional tables, figures and information are available in the Supplementary Material \@ref(supplementary-material).

**Scientific nomenclature**

Scientific names of ticks have been abbreviated as per @dantas-torresStandardizationAbbreviationsGenus2008 (typically utilising the first two letters of the genus, e.g. *Ixodes holocyclus* - *Ix. holocyclus*). 
In order to avoid confusion between two protozoal species of the genera *Trypanosoma* and *Theileria* the abbreviated notation of *Tr.* and *Th.* respectively has been used. 
For consistency these abbreviations have been used throughout the thesis and as a result may differ from published versions.

Mammal common and scientific names follow @jacksonTaxonomyAustralianMammals2015, except where there have since been changes published in the scientific literature. 
Where relevant previous mammal names (common or scientific) are included (denoted by *syn.*); these have been included in cases where the publication cited used different taxa name to those currently accepted, or as deemed relevant.

## Funding & Support {-}

This study was support by the Australian Research Council (LP160100200), Bayer HealthCare (Germany) and Bayer Australia.
Funding was also obtained by The Holsworth Wildlife Research Endowment administered by The Ecological Society of Australia.
This work was supported by resources provided by the Pawsey Supercomputing Centre with funding from the Australian Government and the Government of Western Australia. 
This research was supported by an Australian Government Research Training Program (RTP) Scholarship.

As this thesis includes a number of collaborative projects any additional project funding or support is outlined at the beginning of the chapter.

## Ethics {-}

All animal samples undertaken as part of this project was approved by appropriate institutions. The sampling was conducted under the following animal ethics permits:

- Murdoch University Animal Ethics Committee permit number R3026/18.
- Department of Biodiversity Conservation and Attractions (Western Australian state government) permit numbers 2018/54B, 2018/55B, 2018/57D and 2017/30.
- University of Sydney Animal Ethics Committee Permit number 2018/1429.
- University of Tasmania Animal Ethics Committee permit numbers A0015835 and A0016789
- Department of Primary Industries, Parks, Water and Environment (Tasmanian state government) permit numbers TFA19144 and TFA18028.
- Additional state government permits administered by Department of Parks and Wildlife - license number FO25000045 and 08-002984-1, and authorisation number TFA-2019-0012.


## Funding and support {-}

- Australian Government Research Training Program (RTP) Course fees and Stipend Scholarship.
- Australian Research Council (LP160100200),
- Ecological society of Australia - Holsworth Research Endowment 2018--2020.
- Australian Society for Parasitology - Student Travel Grant 2018 and 2019.
- 5th National Postgraduate Training Workshop in Systematics from Society of Australian Systematic Biologists, Australian Biological Resources Study (ABRS), The University of Adelaide.
- Concepts in Parasitology, Australian Society for Parasitology (place funded by Bayer Australia).


## Attribution Statements {-}

Where manuscripts (including those in preparation) have multiple authors, all authors have been informed of, and consent to, the inclusion of the manuscript. 
As the first author for all chapters included in this thesis I was responsible for the majority of intellectual material. 
Work compiled in this thesis is a result of numerous collaborations and as such an additional *Contribution* section is outlined in the preface of each chapter. This provides specific detail on co-author contributions following the CRediT author statement guidelines^[https://www.elsevier.com/authors/policies-and-guidelines/credit-author-statement].

## List of publications {-}

### Publications arising from this thesis {-}

#### Journal articles {-}

  - **Egan, S.**, Taylor, C., Banks, P., Northover, A., Alhstrom, L., Ryan, U., Irwin, P., and Oskam C. 2021. The bacterial biome of ticks and their wildlife hosts at the urban-wildland interface. *Microbial Genomics*, **7**(12): 000730. DOI: [10.1099/mgen.0.000730](https://doi.org/10.1099/mgen.0.000730)
  - **Egan, S.**, Taylor, C., Austen, J., Banks, P., Northover, A., Alhstrom, L., Ryan, U., Irwin, P., and Oskam C. 2021. Haemoprotozoan surveillance in peri-urban native and introduced wildlife from Australia. *Current Research in Parasitology & Vector-Borne Diseases*, **1**: 100052. DOI: [10.1016/j.crpvbd.2021.100052](https://doi.org/10.1016/j.crpvbd.2021.100052)
  - **Egan, S.**,  Ruiz-Aravena, M., Austen, J., Barton, X., Comte, S., Hamilton, D., Hamede, R., Ryan, U., Irwin, P., Jones, M., and Oskam, C. *2020*. Blood parasites in endangered wildlife: trypanosomes discovered during a survey of haemoprotozoa from the Tasmanian devil. *Pathogens*, **9**(11): 873. DOI: [10.3390/pathogens9110873](https://doi.org/10.3390/pathogens9110873)
  - **Egan, S.**, Taylor, C., Austen, J., Banks, P., Alhstrom, L., Ryan, U., Irwin, P., and Oskam C. 2020. Molecular identification of the *Trypanosoma* (*Herpetosoma*) *lewisi* clade in black rats (*Rattus rattus*) from Australia. *Parasitology Research*, **119**(5): 1691--1696. DOI: [10.1007/s00436-020-06653-z](https://doi.org/10.1007/s00436-020-06653-z)

#### Conference abstracts {-}

**Oral Presentations**

  - **Egan, S.** 2021. The bacterial biome of ticks and their wildlife hosts at the urban-wildland interface. *Global Microbiome: West Coast Microbiome Network*, Perth, Western Australia.
  - **Egan, S.** 2021. What’s in the wildlife? Surveillance of ticks and their associated microbes in Australian wildlife. *14th International Symposium on Ticks and Tick-borne Diseases (Sinnecker-Kunz Early Career Researcher Award Session)*, Germany (hosted online).
  - **Egan, S.**, Fontaine, J., Ryan, U., Irwin., and Oskam C. [2020 - rescheduled to 2022]. Molecular and ecological insights into the ornate kangaroo tick, *Amblyomma triguttatum*. *10th Tick and Tick-borne Pathogen Conference (TTP10)*, Romania.
  - **Egan, S.**, Fontaine, J., Veber, W., Ruthof, K., Ryan, U., Irwin, P., and Oskam, C. 2019. Insights into *Amblyomma triguttatum*. *Combined Biological Sciences Meeting*, Perth, Western Australia.
  - **Egan, S.**, Fontaine, J., Veber, W., Ruthof, K., Ryan, U., Irwin, P., and Oskam, C. 2019. The ecology of *Amblyomma triguttatum triguttatum* in Western Australia. *Australian Society for Parasitology Annual Conference*, Adelaide, South Australia.
  - **Egan, S.**, Evans, M., Irwin, P., and Oskam, C. 2019. Molecular barcoding of Australian hard ticks (Ixodidae). *Australian Society for Parasitology Annual Conference*, Adelaide, South Australia.
  - **Egan, S.**, Siew-May, L., Gillet, A., Banks, P., Ryan U., Irwin, P., and Oskam, C. 2018. Ticks parasitizing Australian wildlife and surveillance of potential tick-borne pathogens. *Australian Society for Parasitology Annual Conference*, Melbourne, Victoria.

**Poster presentations**

  - **Egan, S.**, Loh, S-M., Banks, P., Gillett, A., Ahlstrom, L., Ryan, U., Irwin. P., and Oskam C. [2020 - rescheduled to 2022]. The Australian tick microbiome: highlighting the diversity down under. *10th Tick and Tick-borne Pathogen Conference (TTP10)*, Romania.
  - **Egan, S.**, Greay, T., Gofton, A., Ryan U., Irwin, P., and Oskam, C. 2018. What’s in a tick? Meta-analysis of microbial diversity in Australian ticks. *Global Microbiome II 2018 (West Coast Microbiome Network)*, Perth, Western Australia. 

### List of other publications arising during my candidature {-}

  - **Egan, S.**, Lettoof, D., and Oskam, C. *2022*. First record of the stump-tailed lizard tick, *Amblyomma* *albolimbatum* (Ixodida, Ixodidae) parasitising a human. *Ticks and Tick-Borne Diseases*, **13**(1): 101873. DOI: [10.1016/j.ttbdis.2021.101873](https://doi.org/10.1016/j.ttbdis.2021.101873)
  - Hall, J., Rose, K., Austen, J., **Egan, S.**, Bilney, R., Kambouris, P., MacGregor, C., and Dexter, N. *2021*. Baseline health parameters for a newly established population of long-nosed potoroo (*Potorous tridactylus*) at Booderee National Park, Australia. *Journal of Wildlife Diseases*, **57**(3): 515--524. DOI: [10.7589/JWD-D-20-00168](https://doi.org/10.7589/JWD-D-20-00168)
  - Braima, K., Zahedi, A., **Egan, S.**, Austen, J., Xiao, L., Witham, B., Pingault, N., Perera, S., Oskam, C., Reid, S., and Ryan, U. *2021*. Molecular analysis of cryptosporidiosis cases in Western Australia in 2019 and 2020 supports the occurrence of two swimming pool associated outbreaks and reveals the emergence of a rare *C. hominis* IbA12G3 subtype. *Infection, Genetics and Evolution*, **92**: 104859. DOI: [10.1016/j.meegid.2021.104859](https://doi.org/10.1016/j.meegid.2021.104859)
  - Braima, K., Zahedi, A., Oskam, C., Austen, J., **Egan, S.**, Reid, S., and Ryan, U. 2021. Zoonotic infection by *Cryptosporidium fayeri* IVgA10G1T1R1 in a Western Australian human. *Zoonoses and Public Health*, **68**(4): 358--360. DOI: [10.1111/zph.12806](https://doi.org/10.1111/zph.12806)
  - Boulet, C., **Egan, S.**, Jones, L., Jonsdottir, T., Power, M., Ralph, S., Tran, L., and White, M. 2020^[all authors contributed equally]. Parasitravaganza 2020: Insights into a Virtual Parasitology Conference. *Trends in Parasitology*, **36**(11): 867--875. DOI: [10.1016/j.pt.2020.09.009](https://doi.org/10.1016/j.pt.2020.09.009)
  - Austen, J., Van Kampen E., **Egan, S.**, O'Dea, M., Jackson, B., Ryan, U., Irwin, P., and Prada, D. 2020. First report of *Trypanosoma dionisii* (Trypanosomatidae) identified in Australia. *Parasitology*, **147**(14): 1801--1809. DOI: [10.1017/S0031182020001845](https://doi.org/10.1017/S0031182020001845)
  - **Egan, S.**, Loh, S-M., Banks, P., Gillet, A., Alhstrom, L., Ryan, U., Irwin, P., and Oskam C. 2020. Bacterial community profiling highlights complex diversity and novel organisms in wildlife ticks. *Ticks and Tick-Borne Diseases*, **11**(3):101407. DOI: [10.1016/j.ttbdis.2020.101407](https://doi.org/10.1016/j.ttbdis.2020.101407)
  - Evans, M., **Egan, S.**, Irwin, P., and Oskam, C. 2019. Automatic Barcode Gap Discovery reveals large COI intraspecific divergence in Australian Ixodidae. *Zootaxa*, **4652**(2). DOI: [10.11646/zootaxa.4656.2.13](https://doi.org/10.11646/zootaxa.4656.2.13)
  - Irwin, P., **Egan, S.**, Greay, T., and Oskam C. 2018. Bacterial tick-associated infections in Australia: Current studies and future directions. *Microbiology Australia*, **39**(4): 200--202. DOI: [10.1071/MA18063](https://doi.org/10.1071/MA18063)
  - Siew-May, L., **Egan, S.**, Gillet, A., Banks, P., Ryan U., Irwin, P., and Oskam, C. 2018. Molecular surveillance of piroplasms in ticks from small and medium-sized urban and peri-urban mammals in Australia. *International Journal of Parasitology: Parasites and Wildlife*, **7**(2): 197--203. DOI: [10.1016/j.ijppaw.2018.05.005](https://doi.org/10.1016/j.ijppaw.2018.05.005)